[registry]
version = "1"
updated_at = "2026-06-05"

[[project_types]]
id = "golang"
name = "Go"
version = "0.0.1"
file = "project-types/golang.toml"
sha256 = "363a41b3ebc7653261c1db67be401860619cbbd72dcfadf815d69b7a438182e5"

[[project_types]]
id = "node"
name = "Node"
version = "0.0.1"
file = "project-types/node.toml"
sha256 = "0ab9166ebaeb17bdc09cc01b420bdd88971136eae08c7623b41dae816f470686"

[[project_types]]
id = "rust"
name = "Rust"
version = "0.0.1"
file = "project-types/rust.toml"
sha256 = "82dd6da2492d592b7a10b3fae348f2a6eaaf4d3a9eb979915d9a4b3ae40c8c26"

[[toolchains]]
id = "rust-workspace"
name = "Rust Workspace"
version = "0.0.1"
project_type = "rust"
description = "Cargo workspace with a crates/ directory and an initial library"

[[toolchains.files]]
path = "toolchains/rust-workspace/templates/workspace-root.toml"
sha256 = "3435afac4d68dae74452b74957e5da833705c0bf652e4db07be1e262fdeeec7e"

[[toolchains.files]]
path = "toolchains/rust-workspace/toolchain.toml"
sha256 = "b587018e41d98bc0b190751bb087185e974f1c8250a87a2b9b90d7f5120ee9f9"

[[toolchains]]
id = "vite-react-ts"
name = "Vite + React + TypeScript"
version = "0.0.1"
project_type = "node"

[[toolchains.files]]
path = "toolchains/vite-react-ts/toolchain.toml"
sha256 = "4693bb2fe5e3fb684ddfee068cac666eb8a0f2791d321fabb7400a39a908648c"
